name: Continuous Deployment 

on:
  # pull_request:
  #   types: [closed]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    # if: (github.event.pull_request.merged == 'true') || (github.event.pusher )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v7

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Check that the build exists
        run: ls ./dist/

      - name: Deploy to Netlify 
        uses: nwtgck/actions-netlify@v4.0.0
        with: 
          publish-dir: "./dist"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      

